### ISSUE TITLE
Remove __pycache__ from the repository

### ISSUE THREAD

**Issue by dokempf** [ssciwr/python-project-template#4]
This is currently part of the repo, I think it should be removed and gitignored.

**Comment by dokempf** [comment]
Similarly, I think `doc/build` should not be part of the repository.

**Comment by lkeegan** [comment]
I agree - and I would add a .gitignore such as the github default for python to avoid these kind of files being accidentally commited:
https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by iulusoy** [comment]
> Similarly, I think `doc/build` should not be part of the repository.

I had thought to leave it in there, so users could directly check the sphinx-generated html page after cloning the repository without having to install the requirements.

**Comment by lkeegan** [comment]
> > Similarly, I think `doc/build` should not be part of the repository.
> 
> I had thought to leave it in there, so users could directly check the sphinx-generated html page after cloning the repository without having to install the requirements.

That makes sense, but in general it's a good idea to avoid putting build output / auto-generated files in the git repo as it tends to add noise to commits & pull requests: e.g. someone changes a couple of lines in one source file, builds the docs (with their different local version of sphinx), does `git commit -a`, and makes a pull request which then has hundreds of changed files.

**Comment by dokempf** [comment]
I would also say that the value of the best practice *keep build artifacts out of the repository* outweighs the advantage of being able to look at the docs immediately.
